# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paprika3Mcp < Formula
  desc "MCP Server for creating/editing recipes in Paprika 3 with natural language"
  homepage "https://github.com/soggycactus/paprika-3-mcp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/soggycactus/paprika-3-mcp/releases/download/v0.1.0/paprika-3-mcp_0.1.0_darwin_amd64.zip"
      sha256 "a8d0914dade82339fabf7522562ca127c42ea024d7ada705a5b03afcbc4dd081"

      def install
        bin.install "paprika-3-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/soggycactus/paprika-3-mcp/releases/download/v0.1.0/paprika-3-mcp_0.1.0_darwin_arm64.zip"
      sha256 "ece8e2f0bbc1a2a47e8bf937efedd229a8050580c53b55d4b809d401160bdfe2"

      def install
        bin.install "paprika-3-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soggycactus/paprika-3-mcp/releases/download/v0.1.0/paprika-3-mcp_0.1.0_linux_amd64.zip"
        sha256 "6884779309b1441a8b2cc2c90190f726dbd5f2ba94b423bc810dad9e537ca04b"

        def install
          bin.install "paprika-3-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/soggycactus/paprika-3-mcp/releases/download/v0.1.0/paprika-3-mcp_0.1.0_linux_arm.zip"
        sha256 "63f8a45f2fce1269d715e0376d948660541e0259a6f752f847e0ceb13410e18b"

        def install
          bin.install "paprika-3-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soggycactus/paprika-3-mcp/releases/download/v0.1.0/paprika-3-mcp_0.1.0_linux_arm64.zip"
        sha256 "c5f16635a1108d659ccb99ef7e3f7d8bca87d9fa62d1376f0bc779ccc0210d74"

        def install
          bin.install "paprika-3-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/paprika-3-mcp", "--version"
  end
end
